server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/product_db?authSource=admin
      database: product_db

    redis:
      host: localhost
      port: 6379
      password: password

  cache:
    type: redis

inventory:
  service:
    url: http://localhost:8081

logging:
  level:
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
