server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: inventory-service

logging:
  level:
    org.springframework: INFO

amazon:
  dynamodb:
    endpoint: http://localhost:8000/
    region: us-west-2
  aws:
    access-key: DUMMYIDEXAMPLE
    secret-key: DUMMYEXAMPLEKEY
