import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="sticky top-0 z-50 bg-gradient-to-r from-blue-600 to-blue-500 text-white shadow-lg">
          <div className="px-6 py-3 max-w-7xl mx-auto">
              <div className="flex items-center justify-between">
                  {/* Logo */}
                  <div className="flex items-center space-x-2">
                      <div className="w-8 h-8 bg-white rounded-lg flex items-center justify-center">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-blue-600"
                               viewBox="0 0 20 20" fill="currentColor">
                              <path fillRule="evenodd"
                                    d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z"
                                    clipRule="evenodd"/>
                          </svg>
                      </div>
                      <h1 className="text-xl font-bold text-white">AI Shop</h1>
                  </div>

                  {/* Search Bar */}
                  <div className="relative flex-1 max-w-xl mx-4">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                          <svg className="h-5 w-5 text-blue-400" fill="none" viewBox="0 0 24 24"
                               stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                          </svg>
                      </div>
                      <input
                          type="text"
                          placeholder="Search for products..."
                          className="block w-full pl-10 pr-3 py-2 rounded-full bg-blue-500/20 backdrop-blur-sm border border-blue-400/30 text-white placeholder-blue-200 focus:outline-none focus:ring-2 focus:ring-white focus:bg-blue-500/30 transition-all duration-200"
                      />
                  </div>

                  {/* Navigation */}
                  <div className="flex items-center space-x-5">
                      <button
                          className="p-2 rounded-full hover:bg-blue-500/30 transition-colors duration-200 relative">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-white" fill="none"
                               viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                                    d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"/>
                          </svg>
                          <span
                              className="absolute -top-1 -right-1 bg-white text-blue-600 text-xs font-bold rounded-full h-5 w-5 flex items-center justify-center">3</span>
                      </button>

                      <button className="p-2 rounded-full hover:bg-blue-500/30 transition-colors duration-200">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-white" fill="none"
                               viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                                    d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
                          </svg>
                      </button>

                      {/* User Dropdown */}
                      <div className="relative group">
                          <button className="flex items-center space-x-2 focus:outline-none">
                              <div
                                  className="w-8 h-8 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center text-white font-medium border border-white/30">U
                              </div>
                          </button>

                          <div
                              className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-xl border border-gray-100 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 transform group-hover:translate-y-0 translate-y-1 z-10">
                              <Link href="/orders"
                                    className="block px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 rounded-t-lg transition-colors">My
                                  Orders</Link>
                              <Link href="/account"
                                    className="block px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 transition-colors">Account
                                  Settings</Link>
                              <Link href="/logout"
                                    className="block px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 rounded-b-lg transition-colors">Sign
                                  Out</Link>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </header>
        {children}
      </body>
    </html>
  );
}
