version: '3.8'

services:

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    user: root
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal

volumes:
  dynamodb_data:
